name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approve the deployment to production'
        required: true
        default: ''

jobs:
  deploy:
    if: ${{ github.event.inputs.approval == 'approved' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  request-approval:
    if: ${{ github.event.inputs.approval != 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: peter-evans/wait-on-approval@v2
        with:
          reviewers: azadsekhar7@gmail.com
          message: 'Please review and approve the deployment to production.'
      - name: Deployment approved
        run: echo 'Deployment to production approved.'

