name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      reviewer:
        description: 'The person who needs to approve the deployment to production'
        required: false
        default: ''

jobs:
  deploy:
    if: ${{ github.event.inputs.approval == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and test the application

     # - name: Deploy to production
      #  uses: some-action-to-deploy-to-production

